const products = [
  {
    title: "men shoes",
    image: "https://m.media-amazon.com/images/I/71EoueH5RqL._AC_UL320_.jpg",
    price: 59.99,
    type: "athletic",
    gender: "male",
  },
  {
    title: "men shoes",
    image: "https://m.media-amazon.com/images/I/61FbqzPD8TL._AC_UL320_.jpg",
    price: 20.0,
    type: "athletic",
    gender: "male",
  },
  {
    title: "men shoes",
    image: "https://m.media-amazon.com/images/I/81+SwSx8DSL._AC_UL320_.jpg",
    price: 47.95,
    type: "athletic",
    gender: "male",
  },
  {
    title: "men shoes",
    image: "https://m.media-amazon.com/images/I/81XiBODC84L._AC_UL320_.jpg",
    price: 85.0,
    type: "athletic",
    gender: "male",
  },
  {
    title: "men shoes",
    image: "https://m.media-amazon.com/images/I/711vUQUQ28L._AC_UL320_.jpg",
    price: 120.0,
    type: "classic",
    gender: "male",
  },
  {
    title: "men shoes",
    image: "https://m.media-amazon.com/images/I/81QPe7oDwcL._AC_UL320_.jpg",
    price: 89.99,
    type: "classic",
    gender: "male",
  },
  {
    title: "men shoes",
    image: "https://m.media-amazon.com/images/I/817gA5ZgLgL._AC_UL320_.jpg",
    price: 217.5,
    type: "classic",
    gender: "male",
  },
  {
    title: "men shoes",
    image: "https://m.media-amazon.com/images/I/71vYTTtjBrL._AC_UL320_.jpg",
    price: 162.0,
    type: "classic",
    gender: "male",
  },
  {
    title: "men shoes",
    image: "https://m.media-amazon.com/images/I/71XMq2AJW8L._AC_UL320_.jpg",
    price: 45.0,
    type: "boots",
    gender: "male",
  },
  {
    title: "men shoes",
    image: "https://m.media-amazon.com/images/I/812LnrPWx9L._AC_UL320_.jpg",
    price: 92.0,
    type: "boots",
    gender: "male",
  },
  {
    title: "women shoes",
    image: "https://m.media-amazon.com/images/I/61+d9jIcujL._AC_UL320_.jpg",
    price: 32.98,
    type: "athletic",
    gender: "female",
  },
  {
    title: "women shoes",
    image: "https://m.media-amazon.com/images/I/81OMlQyq8ZL._AC_UL320_.jpg",
    price: 57.34,
    type: "athletic",
    gender: "female",
  },
  {
    title: "women shoes",
    image: "https://m.media-amazon.com/images/I/61pbsE+5OjL._AC_UL320_.jpg",
    price: 73.32,
    type: "athletic",
    gender: "female",
  },
  {
    title: "women shoes",
    image: "https://m.media-amazon.com/images/I/61k5F+2ve-L._AC_UL320_.jpg",
    price: 97.99,
    type: "classic",
    gender: "female",
  },
  {
    title: "women shoes",
    image:
      "https://images-na.ssl-images-amazon.com/images/I/61kIWRPxj9L.__AC_SX395_SY395_QL70_FMwebp_.jpg",
    price: 115.99,
    type: "classic",
    gender: "female",
  },
  {
    title: "women shoes",
    image: "https://m.media-amazon.com/images/I/61acg9tqTyL._AC_UL320_.jpg",
    price: 39.99,
    type: "classic",
    gender: "female",
  },
  {
    title: "women shoes",
    image: "https://m.media-amazon.com/images/I/617GW21CFqS._AC_UL320_.jpg",
    price: 59.99,
    type: "classic",
    gender: "female",
  },
  {
    title: "children shoes",
    image: "https://m.media-amazon.com/images/I/71xOeUzzGqL._AC_UL320_.jpg",
    price: 24.99,
    type: "athletic",
    gender: "children",
  },
  {
    title: "children shoes",
    image: "https://m.media-amazon.com/images/I/710da6zptFL._AC_UL320_.jpg",
    price: 49.99,
    type: "athletic",
    gender: "children",
  },
  {
    title: "children shoes",
    image: "https://m.media-amazon.com/images/I/715VYWzpTKL._AC_UL320_.jpg",
    price: 52.99,
    type: "boots",
    gender: "children",
  },
];
